// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi9MLI6i74CxSsN7VaW2J8lW-z02W-gMM',
    appId: '1:643804735807:web:29c9405d28e29f6c814b8a',
    messagingSenderId: '643804735807',
    projectId: 'protifolio-be322',
    authDomain: 'protifolio-be322.firebaseapp.com',
    storageBucket: 'protifolio-be322.firebasestorage.app',
    measurementId: 'G-Z4998B1BB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2EpzBbutQOMjFDGXCWQfP_3P4YM2-J-k',
    appId: '1:643804735807:android:1ab2c44206820656814b8a',
    messagingSenderId: '643804735807',
    projectId: 'protifolio-be322',
    storageBucket: 'protifolio-be322.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Y83QjovXFk2SCZyIrEOK5BWQDzDxZAQ',
    appId: '1:643804735807:ios:99656e8f606f5c6e814b8a',
    messagingSenderId: '643804735807',
    projectId: 'protifolio-be322',
    storageBucket: 'protifolio-be322.firebasestorage.app',
    iosBundleId: 'com.example.protifolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1Y83QjovXFk2SCZyIrEOK5BWQDzDxZAQ',
    appId: '1:643804735807:ios:99656e8f606f5c6e814b8a',
    messagingSenderId: '643804735807',
    projectId: 'protifolio-be322',
    storageBucket: 'protifolio-be322.firebasestorage.app',
    iosBundleId: 'com.example.protifolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi9MLI6i74CxSsN7VaW2J8lW-z02W-gMM',
    appId: '1:643804735807:web:a502b294ec76eafc814b8a',
    messagingSenderId: '643804735807',
    projectId: 'protifolio-be322',
    authDomain: 'protifolio-be322.firebaseapp.com',
    storageBucket: 'protifolio-be322.firebasestorage.app',
    measurementId: 'G-RLHM2KY3GT',
  );
}
